### ISSUE TITLE
jquery 1.8 support

### ISSUE THREAD

**Issue by jterrace** [louisremi/jquery-smartresize#1]
First, let me just say thanks for this library. It's awesome.

It seems to be broken for me with jQuery 1.8. I only get a single throttledresize event instead of the expected 60fps. It works perfectly with 1.7.2.

There are no errors on the console. I just don't get the throttledresize event.

**Comment by louisremi** [comment]
Oh... second plugin broken by 1.8
I guess this is because I use .animate() to loop, and the part of the code has changed a lot.
I'll investigate, but I'm currently very busy.

**Comment by jterrace** [comment]
No problem, I'm just using 1.7.2 for now, but I figured I'd file the issue to let you know, thanks!

**Comment by louisremi** [comment]
Thanks for letting me know yes.
I just found a workaround and pushed a fix.
I'll change the script in the download section.

Can you then confirm that the latest version solves your problem with 1.8?

Thank you in advance

**Comment by jterrace** [comment]
Confirmed working perfectly now in 1.8.0. Thanks!

**Comment by jterrace** [comment]
For future reference, fixed in f1798f24c63b3857151116bf8933e7700321e2e5
