### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by dnwhte** [louisremi/jquery-smartresize#2]
I'm having trouble using the minimal standalone version with multiple instances. I'm no JS expert, so I'm probably missing something obvious. But if I do the following, all that gets logged is "second". How can I get both to work without having them within the same function call?

```
function on_resize(c,t){onresize=function(){clearTimeout(t);t=setTimeout(c,300)};return c};

on_resize(function(){
    log('first');
});
on_resize(function(){
    log('second');
});
```

**Comment by louisremi** [comment]
The answer is simple: you can't. If you want to use multiple instances you should use the standard version.
